spring.application.name=sb-Ecom2

#spring.h2.console.enabled=true

#spring.datasource.url=jdbc:postgresql://localhost:5432/sb-ecom
#spring.datasource.username=postgres
#spring.datasource.password=Anapple27



spring.datasource.url=jdbc:postgresql://dpg-d9phh5flk1mc73e4amf0-a.frankfurt-postgres.render.com:5432/sb_test_ecom?sslmode=require
spring.datasource.username=sb_test_ecom_user
spring.datasource.password=r0QFgsSvqBsJJAUYWAI67k2B7XgrJYTA
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.app.jwtSecret=QWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZw==
spring.app.jwtExpirationMs=300000
spring.app.jwtCookie=springEcom

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.sql=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.abdelrahman027.sbecom2=DEBUG

server.port=8080

